### PR TITLE
feat: [CO-499] Remove both and mixed mode form web proxy config

### PR DESCRIPTION
**Pull request by keshavbhatt**
**What has changed:**
- cleanup of http config template as full config is no longer required 
- mixed and both mode templates are no longer required hence deleted
- http only mode in web proxy is no longer supported but the template was kept to support redirect mode.

**Related PRs:**
- https://github.com/Zextras/carbonio-mailbox/pull/155

### CODE REVIEW

**Review by Polpetta — APPROVED** [review]
I trust you on this one ;)

**Review by aheeva-yuliya — APPROVED** [review]

**Comment by frisonisland** [comment]
@keshavbhatt generally speaking changes make sense to me, but it's not clear the role about "mode" files and if we still need them. This is a list of the files for web directives:

/opt/zextras/conf/nginx/includes/nginx.conf.web
/opt/zextras/conf/nginx/includes/nginx.conf.web.admin
/opt/zextras/conf/nginx/includes/nginx.conf.web.admin.default
/opt/zextras/conf/nginx/includes/nginx.conf.web.carbonio.admin
/opt/zextras/conf/nginx/includes/nginx.conf.web.carbonio.admin.default
/opt/zextras/conf/nginx/includes/nginx.conf.web.http
/opt/zextras/conf/nginx/includes/nginx.conf.web.http.default
/opt/zextras/conf/nginx/includes/nginx.conf.web.http.mode-both
**/opt/zextras/conf/nginx/includes/nginx.conf.web.http.mode-http
/opt/zextras/conf/nginx/includes/nginx.conf.web.http.mode-https**
/opt/zextras/conf/nginx/includes/nginx.conf.web.http.mode-mixed
**/opt/zextras/conf/nginx/includes/nginx.conf.web.http.mode-redirect**
/opt/zextras/conf/nginx/includes/nginx.conf.web.https
/opt/zextras/conf/nginx/includes/nginx.conf.web.https.default
/opt/zextras/conf/nginx/includes/nginx.conf.web.https.mode-both
**/opt/zextras/conf/nginx/includes/nginx.conf.web.https.mode-http**
/opt/zextras/conf/nginx/includes/nginx.conf.web.https.mode-https
/opt/zextras/conf/nginx/includes/nginx.conf.web.https.mode-mixed
**/opt/zextras/conf/nginx/includes/nginx.conf.web.https.mode-redirect**
/opt/zextras/conf/nginx/includes/nginx.conf.web.sso
/opt/zextras/conf/nginx/includes/nginx.conf.web.sso.default

Looking at the files in bold, like nginx.conf.web.https.mode-http, I wonder if we can get rid of them.
Also couldn't the default http configuration just redirect to https without the need of 
`include ${core.includes}/${core.cprefix}.web.http.mode-${web.mailmode};`?

**Comment by keshavbhatt** [comment]
> Looking at the files in bold, like nginx.conf.web.https.mode-http, I wonder if we can get rid of them.
> Also couldn't the default http configuration just redirect to https without the need of
> `include ${core.includes}/${core.cprefix}.web.http.mode-${web.mailmode};`?

Generally speaking, nginx dont care how many files you want to split the configuration into. The concept of splitting is just to seperate the concerns and make things little confusing by putting everything in one place. In this case we have the same situation. We can do more cleanup but keeping few of those files help keeping things clear(I am also in favour of removing those empty files in future). Lets stay in the scope of this ticket for now, we have one more where we will check mentioned possibilities.

**Comment by frisonisland** [comment]
> > Looking at the files in bold, like nginx.conf.web.https.mode-http, I wonder if we can get rid of them.
> > Also couldn't the default http configuration just redirect to https without the need of
> > `include ${core.includes}/${core.cprefix}.web.http.mode-${web.mailmode};`?
> 
> Generally speaking, nginx dont care how many files you want to split the configuration into. The concept of splitting is just to seperate the concerns and make things little confusing by putting everything in one place. In this case we have the same situation. We can do more cleanup but keeping few of those files help keeping things clear(I am also in favour of removing those empty files in future). Lets stay in the scope of this ticket for now, we have one more where we will check mentioned possibilities.

Yes, it's not about splitting into multiple files, it's about if "mode-redirect" and "mode-http" are still relevant!
But ok if these changes work I'm in favor of removing mentioned files in another iteration :slightly_smiling_face:

**Pull request merged**
